### ISSUE TITLE
minor problem with the converting

### ISSUE THREAD

**Issue by francispoulin** [amitsaha/jupyter-notebook-slides#1]
First, thanks for sharing this with everyone.  It looks great!

I have been able to view your sample and am also working on my own.  The good news is that it does convert and I can view it. The bad  news is that I do get an error.  I have copied the message below.  Do you have any suggestions as to how I might fix this?

jupyter-notebook-slides$ jupyter-nbconvert --to slides Testing.ipynb --reveal-prefix=reveal.js --post serve
[NbConvertApp] Converting notebook Testing.ipynb to slides
[NbConvertApp] Writing 253388 bytes to Testing.slides.html
[NbConvertApp] Serving local reveal.js
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 457, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 430, in convert_single_notebook
    self.postprocess_single_notebook(write_results)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 402, in postprocess_single_notebook
    self.postprocessor(write_results)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/postprocessors/base.py", line 28, in __call__
    self.postprocess(input)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/postprocessors/serve.py", line 87, in postprocess
    http_server.listen(self.port, address=self.ip)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 182, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by francispoulin** [comment]
I realized that if I killed the jupyter-notebook jobs running then the error went away.

Sorry for the bother.
